
[terminal.shell]
program = "/usr/bin/fish"

[font]
# normal = { family = "GohuFont14 Nerd Font Mono", style = "Regular" }
# size = 10.5

normal = { family = "ProggyClean Nerd Font Mono", style = "Regular" }
size = 12

[window]
dimensions = { columns = 120, lines = 100 }

[terminal]
